main: me.JakeyTheDev.Core.Core
name: Cove-Core
version: 1.1
author: JakeyTheDev
commands: 
   gamemode:
      usage: /<command> [player name] [int]
      description: Sets the gamemode for you or a fellow player
      aliases: [gm]
   setrank:
      usage: /<command> <player> <rank>
      description: Set rank of a player
   eco:
      usage: /<command>
      description: Admistrate a users balance.
   youtube: